from dataclasses import dataclass, field


@dataclass
class TieredKeywords:
    high: list[str] = field(default_factory=list)
    medium: list[str] = field(default_factory=list)
    low: list[str] = field(default_factory=list)


@dataclass
class NegativeKeywords:
    hard_exclude: list[str] = field(default_factory=list)
    soft_exclude: list[str] = field(default_factory=list)


@dataclass
class KeywordConfig:
    role_titles: TieredKeywords = field(default_factory=TieredKeywords)
    technologies: TieredKeywords = field(default_factory=TieredKeywords)
    domain_skills: TieredKeywords = field(default_factory=TieredKeywords)
    seniority_signals: TieredKeywords = field(default_factory=TieredKeywords)
    negative_keywords: NegativeKeywords = field(default_factory=NegativeKeywords)


SCORE_WEIGHTS: dict[str, float] = {
    "high": 3,
    "medium": 1,
    "low": 0.5,
    "hard_exclude": -10,
    "soft_exclude": -2,
    "normalizer": 30,
}

keyword_config = KeywordConfig(
    role_titles=TieredKeywords(
        high=[
            "senior frontend engineer",
            "senior front-end engineer",
            "senior front end engineer",
            "staff frontend engineer",
            "staff front-end engineer",
            "frontend lead",
            "lead frontend engineer",
            "senior fullstack engineer",
            "senior full-stack engineer",
            "senior full stack engineer",
            "staff fullstack engineer",
            "senior ui engineer",
            "senior frontend developer",
            "senior full stack developer",
            "frontend architect",
            "senior software engineer, frontend",
            "senior software engineer - frontend",
            "senior react engineer",
            "senior react developer",
            "design systems engineer",
            "principal frontend engineer",
            "staff software engineer, frontend",
        ],
        medium=[
            "frontend engineer",
            "front-end engineer",
            "fullstack engineer",
            "full stack developer",
            "ui engineer",
            "web engineer",
            "software engineer - web",
            "frontend developer",
            "full-stack developer",
            "javascript engineer",
            "typescript engineer",
            "senior software engineer",
            "staff software engineer",
            "web developer",
        ],
        low=[
            "software engineer",
            "application developer",
            "web application engineer",
        ],
    ),
    technologies=TieredKeywords(
        high=[
            "react",
            "react.js",
            "reactjs",
            "next.js",
            "nextjs",
            "typescript",
            "tailwind",
            "tailwind css",
            "tailwindcss",
            "node.js",
            "nodejs",
            "postgresql",
            "postgres",
        ],
        medium=[
            "javascript",
            "graphql",
            "rest",
            "restful",
            "storybook",
            "jest",
            "playwright",
            "cypress",
            "webpack",
            "vite",
            "turborepo",
            "nx",
            "gsap",
            "css-in-js",
            "styled-components",
            "sass",
            "scss",
            "redux",
            "zustand",
            "express",
            "prisma",
            "vercel",
            "aws",
            "docker",
            "git",
            "ci/cd",
            "github actions",
            "react testing library",
            "figma",
            "sentry",
            "mdx",
        ],
        low=[
            "python",
            "go",
            "golang",
            "ruby",
            "redis",
            "mongodb",
            "mysql",
            "terraform",
            "kubernetes",
            "remix",
            "astro",
            "svelte",
        ],
    ),
    domain_skills=TieredKeywords(
        high=[
            "design system",
            "design systems",
            "component library",
            "component libraries",
            "accessibility",
            "a11y",
            "wcag",
            "aria",
            "performance optimization",
            "core web vitals",
            "web performance",
            "monorepo",
            "shared ui",
            "ui library",
        ],
        medium=[
            "responsive design",
            "responsive web",
            "mobile-first",
            "cross-browser",
            "server-side rendering",
            "ssr",
            "ssg",
            "static generation",
            "seo",
            "internationalization",
            "i18n",
            "spa",
            "single-page",
            "micro-frontend",
            "progressive enhancement",
            "code review",
            "unit testing",
            "e2e testing",
            "api design",
            "frontend architecture",
            "web standards",
            "semantic html",
        ],
    ),
    seniority_signals=TieredKeywords(
        high=[
            "architect",
            "architecture",
            "technical lead",
            "tech lead",
            "mentor",
            "technical direction",
            "cross-functional",
            "system design",
            "lead engineer",
            "principal",
            "staff",
            "senior",
            "ownership",
        ],
        medium=[
            "stakeholder",
            "roadmap",
            "strategy",
            "code review",
            "best practices",
            "standards",
            "scalable",
            "large-scale",
            "complex",
            "high-traffic",
            "team lead",
            "influence",
            "decision-making",
            "tradeoffs",
        ],
    ),
    negative_keywords=NegativeKeywords(
        hard_exclude=[
            "angular only",
            "vue.js required",
            "vue only",
            "c#",
            ".net",
            "java required",
            "ios developer",
            "android developer",
            "mobile native",
            "swift required",
            "kotlin required",
            "flutter",
            "react native only",
            "junior",
            "intern",
            "internship",
            "entry-level",
            "entry level",
            "new grad",
            "associate developer",
        ],
        soft_exclude=[
            "angular",
            "vue.js",
            "vue",
            "java",
            "php",
            "wordpress",
            "drupal",
            "salesforce",
            "sap",
            "oracle",
            "embedded",
            "firmware",
            "blockchain",
            "web3",
            "solidity",
            "game engine",
            "unity",
            "unreal",
            "security clearance",
            "on-site only",
            "no remote",
        ],
    ),
)
