import { AllowedBlogSlugs, BlogStructuredData } from '@/types/base';
import { blogSlugs, blogPageSlugs } from '@/data/blog';
import { blogRecords } from '@/data/blogThumbnails';
import { DOMAIN_URL, BLOG_LINK, FULL_NAME } from '@/utils/constants';
import { blogMdxMetadata } from '@/data/content/blog';
import {
  personStructuredData as author,
  CollectionPageStructuredData,
} from './base';

export const blogStructuredData: Record<AllowedBlogSlugs, BlogStructuredData> =
  {
    [blogSlugs.unifiedContentPipeline]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.unifiedContentPipeline].title,
      description: blogRecords[blogSlugs.unifiedContentPipeline].description,
      datePublished:
        blogMdxMetadata[blogSlugs.unifiedContentPipeline]?.date ?? '',
      author,
    },
    [blogSlugs.autoGeneratedTocScrollSpy]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.autoGeneratedTocScrollSpy].title,
      description: blogRecords[blogSlugs.autoGeneratedTocScrollSpy].description,
      datePublished:
        blogMdxMetadata[blogSlugs.autoGeneratedTocScrollSpy]?.date ?? '',
      author,
    },
    [blogSlugs.visualRegressionCiPipeline]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.visualRegressionCiPipeline].title,
      description:
        blogRecords[blogSlugs.visualRegressionCiPipeline].description,
      datePublished:
        blogMdxMetadata[blogSlugs.visualRegressionCiPipeline]?.date ?? '',
      author,
    },
    [blogSlugs.sharedUiDesignSystem]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.sharedUiDesignSystem].title,
      description: blogRecords[blogSlugs.sharedUiDesignSystem].description,
      datePublished:
        blogMdxMetadata[blogSlugs.sharedUiDesignSystem]?.date ?? '',
      author,
    },
    [blogSlugs.composeProvidersReactContext]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.composeProvidersReactContext].title,
      description:
        blogRecords[blogSlugs.composeProvidersReactContext].description,
      datePublished:
        blogMdxMetadata[blogSlugs.composeProvidersReactContext]?.date ?? '',
      author,
    },
    [blogSlugs.typographySystemNextjs]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.typographySystemNextjs].title,
      description: blogRecords[blogSlugs.typographySystemNextjs].description,
      datePublished:
        blogMdxMetadata[blogSlugs.typographySystemNextjs]?.date ?? '',
      author,
    },
    [blogSlugs.removingFocusTrapReact]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.removingFocusTrapReact].title,
      description: blogRecords[blogSlugs.removingFocusTrapReact].description,
      datePublished:
        blogMdxMetadata[blogSlugs.removingFocusTrapReact]?.date ?? '',
      author,
    },
    [blogSlugs.eslintImportOrderingMonorepo]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.eslintImportOrderingMonorepo].title,
      description:
        blogRecords[blogSlugs.eslintImportOrderingMonorepo].description,
      datePublished:
        blogMdxMetadata[blogSlugs.eslintImportOrderingMonorepo]?.date ?? '',
      author,
    },
    [blogSlugs.ruleOfThreeDesignSystems]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.ruleOfThreeDesignSystems].title,
      description: blogRecords[blogSlugs.ruleOfThreeDesignSystems].description,
      datePublished:
        blogMdxMetadata[blogSlugs.ruleOfThreeDesignSystems]?.date ?? '',
      author,
    },
    [blogSlugs.documentingDesignTokens]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.documentingDesignTokens].title,
      description: blogRecords[blogSlugs.documentingDesignTokens].description,
      datePublished:
        blogMdxMetadata[blogSlugs.documentingDesignTokens]?.date ?? '',
      author,
    },
    [blogSlugs.accessibleDropdownKeyboardNav]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.accessibleDropdownKeyboardNav].title,
      description:
        blogRecords[blogSlugs.accessibleDropdownKeyboardNav].description,
      datePublished:
        blogMdxMetadata[blogSlugs.accessibleDropdownKeyboardNav]?.date ?? '',
      author,
    },
    [blogSlugs.toastPauseOnHover]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.toastPauseOnHover].title,
      description: blogRecords[blogSlugs.toastPauseOnHover].description,
      datePublished: blogMdxMetadata[blogSlugs.toastPauseOnHover]?.date ?? '',
      author,
    },
    [blogSlugs.keyboardNavigableDataTables]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.keyboardNavigableDataTables].title,
      description:
        blogRecords[blogSlugs.keyboardNavigableDataTables].description,
      datePublished:
        blogMdxMetadata[blogSlugs.keyboardNavigableDataTables]?.date ?? '',
      author,
    },
    [blogSlugs.importTypeCircularDependency]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.importTypeCircularDependency].title,
      description:
        blogRecords[blogSlugs.importTypeCircularDependency].description,
      datePublished:
        blogMdxMetadata[blogSlugs.importTypeCircularDependency]?.date ?? '',
      author,
    },
    [blogSlugs.mobileBottomNavZIndex]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.mobileBottomNavZIndex].title,
      description: blogRecords[blogSlugs.mobileBottomNavZIndex].description,
      datePublished:
        blogMdxMetadata[blogSlugs.mobileBottomNavZIndex]?.date ?? '',
      author,
    },
    [blogSlugs.gracefulDegradationThirdPartyEmbeds]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline:
        blogRecords[blogSlugs.gracefulDegradationThirdPartyEmbeds].title,
      description:
        blogRecords[blogSlugs.gracefulDegradationThirdPartyEmbeds].description,
      datePublished:
        blogMdxMetadata[blogSlugs.gracefulDegradationThirdPartyEmbeds]?.date ??
        '',
      author,
    },
    [blogSlugs.hydrationMismatchUseSyncedState]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.hydrationMismatchUseSyncedState].title,
      description:
        blogRecords[blogSlugs.hydrationMismatchUseSyncedState].description,
      datePublished:
        blogMdxMetadata[blogSlugs.hydrationMismatchUseSyncedState]?.date ?? '',
      author,
    },
    [blogSlugs.mobileNavA11yBottomSheet]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.mobileNavA11yBottomSheet].title,
      description: blogRecords[blogSlugs.mobileNavA11yBottomSheet].description,
      datePublished:
        blogMdxMetadata[blogSlugs.mobileNavA11yBottomSheet]?.date ?? '',
      author,
    },
    [blogSlugs.faviconPipelineOneSvg]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.faviconPipelineOneSvg].title,
      description: blogRecords[blogSlugs.faviconPipelineOneSvg].description,
      datePublished:
        blogMdxMetadata[blogSlugs.faviconPipelineOneSvg]?.date ?? '',
      author,
    },
    [blogSlugs.standardizingComponentSizeScale]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.standardizingComponentSizeScale].title,
      description:
        blogRecords[blogSlugs.standardizingComponentSizeScale].description,
      datePublished:
        blogMdxMetadata[blogSlugs.standardizingComponentSizeScale]?.date ?? '',
      author,
    },
    [blogSlugs.formApiAlignmentAria]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.formApiAlignmentAria].title,
      description: blogRecords[blogSlugs.formApiAlignmentAria].description,
      datePublished:
        blogMdxMetadata[blogSlugs.formApiAlignmentAria]?.date ?? '',
      author,
    },
    [blogSlugs.tooltipAriaDescribedbyWrongElement]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.tooltipAriaDescribedbyWrongElement].title,
      description:
        blogRecords[blogSlugs.tooltipAriaDescribedbyWrongElement].description,
      datePublished:
        blogMdxMetadata[blogSlugs.tooltipAriaDescribedbyWrongElement]?.date ??
        '',
      author,
    },
    [blogSlugs.ciDocsOnlyShellDetection]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.ciDocsOnlyShellDetection].title,
      description: blogRecords[blogSlugs.ciDocsOnlyShellDetection].description,
      datePublished:
        blogMdxMetadata[blogSlugs.ciDocsOnlyShellDetection]?.date ?? '',
      author,
    },
    [blogSlugs.calendlyEmbedTimeoutFallback]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.calendlyEmbedTimeoutFallback].title,
      description:
        blogRecords[blogSlugs.calendlyEmbedTimeoutFallback].description,
      datePublished:
        blogMdxMetadata[blogSlugs.calendlyEmbedTimeoutFallback]?.date ?? '',
      author,
    },
    [blogSlugs.pnpmPhantomDependencies]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.pnpmPhantomDependencies].title,
      description: blogRecords[blogSlugs.pnpmPhantomDependencies].description,
      datePublished:
        blogMdxMetadata[blogSlugs.pnpmPhantomDependencies]?.date ?? '',
      author,
    },
    [blogSlugs.staticSiteSearchCmdk]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.staticSiteSearchCmdk].title,
      description: blogRecords[blogSlugs.staticSiteSearchCmdk].description,
      datePublished:
        blogMdxMetadata[blogSlugs.staticSiteSearchCmdk]?.date ?? '',
      author,
    },
    [blogSlugs.prefersReducedMotionComponentLibrary]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline:
        blogRecords[blogSlugs.prefersReducedMotionComponentLibrary].title,
      description:
        blogRecords[blogSlugs.prefersReducedMotionComponentLibrary].description,
      datePublished:
        blogMdxMetadata[blogSlugs.prefersReducedMotionComponentLibrary]?.date ??
        '',
      author,
    },
    [blogSlugs.cyclingThemeToggle]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.cyclingThemeToggle].title,
      description: blogRecords[blogSlugs.cyclingThemeToggle].description,
      datePublished: blogMdxMetadata[blogSlugs.cyclingThemeToggle]?.date ?? '',
      author,
    },
    [blogSlugs.minisearchRankedSearchCmdk]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.minisearchRankedSearchCmdk].title,
      description:
        blogRecords[blogSlugs.minisearchRankedSearchCmdk].description,
      datePublished:
        blogMdxMetadata[blogSlugs.minisearchRankedSearchCmdk]?.date ?? '',
      author,
    },
    [blogSlugs.funnelSessionIdAnalytics]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.funnelSessionIdAnalytics].title,
      description: blogRecords[blogSlugs.funnelSessionIdAnalytics].description,
      datePublished:
        blogMdxMetadata[blogSlugs.funnelSessionIdAnalytics]?.date ?? '',
      author,
    },
  };

export const blogRootStructuredData: CollectionPageStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'CollectionPage',
  name: `Blog | ${FULL_NAME} - Full-Stack Engineer`,
  description:
    "Notes from shipping code. Deep-dives on the problems I've debugged, the patterns I've extracted, and the decisions I'd make differently next time.",
  url: `${DOMAIN_URL}${BLOG_LINK.href}`,
  author,
  mainEntity: {
    '@type': 'ItemList',
    itemListElement: blogPageSlugs.map((slug, index) => ({
      '@type': 'ListItem' as const,
      position: index + 1,
      name: blogRecords[slug].title,
      url: `${DOMAIN_URL}${BLOG_LINK.href}/${slug}`,
      description: blogRecords[slug].description as string,
    })),
  },
};
