import { AllowedBlogSlugs, BlogStructuredData } from '@/types/base';
import { blogSlugs, blogPageSlugs } from '@/data/blog';
import { blogRecords } from '@/data/blogThumbnails';
import { DOMAIN_URL, BLOG_LINK, FULL_NAME } from '@/utils/constants';
import { blogMdxMetadata } from '@/data/content/blog';
import {
  personStructuredData as author,
  CollectionPageStructuredData,
} from './base';

export const blogStructuredData: Record<AllowedBlogSlugs, BlogStructuredData> =
  {
    [blogSlugs.unifiedContentPipeline]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.unifiedContentPipeline].title,
      description: blogRecords[blogSlugs.unifiedContentPipeline].description,
      datePublished:
        blogMdxMetadata[blogSlugs.unifiedContentPipeline]?.date ?? '',
      author,
    },
    [blogSlugs.autoGeneratedTocScrollSpy]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.autoGeneratedTocScrollSpy].title,
      description: blogRecords[blogSlugs.autoGeneratedTocScrollSpy].description,
      datePublished:
        blogMdxMetadata[blogSlugs.autoGeneratedTocScrollSpy]?.date ?? '',
      author,
    },
    [blogSlugs.visualRegressionCiPipeline]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.visualRegressionCiPipeline].title,
      description:
        blogRecords[blogSlugs.visualRegressionCiPipeline].description,
      datePublished:
        blogMdxMetadata[blogSlugs.visualRegressionCiPipeline]?.date ?? '',
      author,
    },
    [blogSlugs.sharedUiDesignSystem]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.sharedUiDesignSystem].title,
      description: blogRecords[blogSlugs.sharedUiDesignSystem].description,
      datePublished:
        blogMdxMetadata[blogSlugs.sharedUiDesignSystem]?.date ?? '',
      author,
    },
    [blogSlugs.composeProvidersReactContext]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.composeProvidersReactContext].title,
      description:
        blogRecords[blogSlugs.composeProvidersReactContext].description,
      datePublished:
        blogMdxMetadata[blogSlugs.composeProvidersReactContext]?.date ?? '',
      author,
    },
    [blogSlugs.typographySystemNextjs]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.typographySystemNextjs].title,
      description: blogRecords[blogSlugs.typographySystemNextjs].description,
      datePublished:
        blogMdxMetadata[blogSlugs.typographySystemNextjs]?.date ?? '',
      author,
    },
    [blogSlugs.removingFocusTrapReact]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.removingFocusTrapReact].title,
      description: blogRecords[blogSlugs.removingFocusTrapReact].description,
      datePublished:
        blogMdxMetadata[blogSlugs.removingFocusTrapReact]?.date ?? '',
      author,
    },
    [blogSlugs.eslintImportOrderingMonorepo]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.eslintImportOrderingMonorepo].title,
      description:
        blogRecords[blogSlugs.eslintImportOrderingMonorepo].description,
      datePublished:
        blogMdxMetadata[blogSlugs.eslintImportOrderingMonorepo]?.date ?? '',
      author,
    },
    [blogSlugs.ruleOfThreeDesignSystems]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.ruleOfThreeDesignSystems].title,
      description: blogRecords[blogSlugs.ruleOfThreeDesignSystems].description,
      datePublished:
        blogMdxMetadata[blogSlugs.ruleOfThreeDesignSystems]?.date ?? '',
      author,
    },
    [blogSlugs.documentingDesignTokens]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.documentingDesignTokens].title,
      description: blogRecords[blogSlugs.documentingDesignTokens].description,
      datePublished:
        blogMdxMetadata[blogSlugs.documentingDesignTokens]?.date ?? '',
      author,
    },
    [blogSlugs.accessibleDropdownKeyboardNav]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.accessibleDropdownKeyboardNav].title,
      description:
        blogRecords[blogSlugs.accessibleDropdownKeyboardNav].description,
      datePublished:
        blogMdxMetadata[blogSlugs.accessibleDropdownKeyboardNav]?.date ?? '',
      author,
    },
    [blogSlugs.toastPauseOnHover]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.toastPauseOnHover].title,
      description: blogRecords[blogSlugs.toastPauseOnHover].description,
      datePublished: blogMdxMetadata[blogSlugs.toastPauseOnHover]?.date ?? '',
      author,
    },
    [blogSlugs.keyboardNavigableDataTables]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.keyboardNavigableDataTables].title,
      description:
        blogRecords[blogSlugs.keyboardNavigableDataTables].description,
      datePublished:
        blogMdxMetadata[blogSlugs.keyboardNavigableDataTables]?.date ?? '',
      author,
    },
    [blogSlugs.importTypeCircularDependency]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.importTypeCircularDependency].title,
      description:
        blogRecords[blogSlugs.importTypeCircularDependency].description,
      datePublished:
        blogMdxMetadata[blogSlugs.importTypeCircularDependency]?.date ?? '',
      author,
    },
    [blogSlugs.mobileBottomNavZIndex]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: blogRecords[blogSlugs.mobileBottomNavZIndex].title,
      description: blogRecords[blogSlugs.mobileBottomNavZIndex].description,
      datePublished:
        blogMdxMetadata[blogSlugs.mobileBottomNavZIndex]?.date ?? '',
      author,
    },
    [blogSlugs.gracefulDegradationThirdPartyEmbeds]: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline:
        blogRecords[blogSlugs.gracefulDegradationThirdPartyEmbeds].title,
      description:
        blogRecords[blogSlugs.gracefulDegradationThirdPartyEmbeds].description,
      datePublished:
        blogMdxMetadata[blogSlugs.gracefulDegradationThirdPartyEmbeds]?.date ??
        '',
      author,
    },
  };

export const blogRootStructuredData: CollectionPageStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'CollectionPage',
  name: `Blog | ${FULL_NAME} - Full-Stack Engineer`,
  description:
    'Technical deep-dives, opinions on frontend trends, tutorials, and lessons learned from a full-stack engineer.',
  url: `${DOMAIN_URL}${BLOG_LINK.href}`,
  author,
  mainEntity: {
    '@type': 'ItemList',
    itemListElement: blogPageSlugs.map((slug, index) => ({
      '@type': 'ListItem' as const,
      position: index + 1,
      name: blogRecords[slug].title,
      url: `${DOMAIN_URL}${BLOG_LINK.href}/${slug}`,
      description: blogRecords[slug].description as string,
    })),
  },
};
