import { ComponentType } from 'react';
import { AllowedBlogSlugs } from '@/types/base';
import { PostMetadata } from '@/types/postTypes';
import UnifiedContentPipeline, {
  metadata as unifiedPipelineMeta,
} from './unified-content-pipeline.mdx';
import AutoGeneratedTocScrollSpy, {
  metadata as tocScrollSpyMeta,
} from './auto-generated-toc-scroll-spy.mdx';
import VisualRegressionCiPipeline, {
  metadata as visualRegressionMeta,
} from './visual-regression-ci-pipeline.mdx';

import SharedUiDesignSystem, {
  metadata as sharedUiDesignSystemMeta,
} from './shared-ui-design-system.mdx';

export const blogMdxComponents: Record<AllowedBlogSlugs, ComponentType> = {
  'unified-content-pipeline': UnifiedContentPipeline,
  'auto-generated-toc-scroll-spy': AutoGeneratedTocScrollSpy,
  'visual-regression-ci-pipeline': VisualRegressionCiPipeline,
  'shared-ui-design-system': SharedUiDesignSystem,
};

export const blogMdxMetadata: Record<AllowedBlogSlugs, PostMetadata> = {
  'unified-content-pipeline': unifiedPipelineMeta,
  'auto-generated-toc-scroll-spy': tocScrollSpyMeta,
  'visual-regression-ci-pipeline': visualRegressionMeta,
  'shared-ui-design-system': sharedUiDesignSystemMeta,
};
