import { ComponentType } from 'react';
import { AllowedBlogSlugs } from '@/types/base';
import { PostMetadata } from '@/types/postTypes';
import UnifiedContentPipeline, {
  metadata as unifiedPipelineMeta,
} from './unified-content-pipeline.mdx';
import AutoGeneratedTocScrollSpy, {
  metadata as tocScrollSpyMeta,
} from './auto-generated-toc-scroll-spy.mdx';
import VisualRegressionCiPipeline, {
  metadata as visualRegressionMeta,
} from './visual-regression-ci-pipeline.mdx';
import SharedUiDesignSystem, {
  metadata as sharedUiDesignSystemMeta,
} from './shared-ui-design-system.mdx';
import ComposeProvidersReactContext, {
  metadata as composeProvidersMeta,
} from './compose-providers-react-context.mdx';
import TypographySystemNextjs, {
  metadata as typographySystemMeta,
} from './typography-system-nextjs.mdx';
import RemovingFocusTrapReact, {
  metadata as removingFocusTrapMeta,
} from './removing-focus-trap-react.mdx';
import EslintImportOrderingMonorepo, {
  metadata as eslintImportOrderingMeta,
} from './eslint-import-ordering-monorepo.mdx';
import RuleOfThreeDesignSystems, {
  metadata as ruleOfThreeMeta,
} from './rule-of-three-design-systems.mdx';
import DocumentingDesignTokens, {
  metadata as documentingDesignTokensMeta,
} from './documenting-design-tokens.mdx';
import AccessibleDropdownKeyboardNav, {
  metadata as accessibleDropdownMeta,
} from './accessible-dropdown-keyboard-nav.mdx';
import ToastPauseOnHover, {
  metadata as toastPauseOnHoverMeta,
} from './toast-pause-on-hover.mdx';
import KeyboardNavigableDataTables, {
  metadata as keyboardNavigableTablesMeta,
} from './keyboard-navigable-data-tables.mdx';
import ImportTypeCircularDependency, {
  metadata as importTypeCircularDependencyMeta,
} from './import-type-circular-dependency.mdx';
import MobileBottomNavZIndex, {
  metadata as mobileBottomNavZIndexMeta,
} from './mobile-bottom-nav-z-index.mdx';
import GracefulDegradationThirdPartyEmbeds, {
  metadata as gracefulDegradationMeta,
} from './graceful-degradation-third-party-embeds.mdx';
import HydrationMismatchUseSyncedState, {
  metadata as hydrationMismatchMeta,
} from './hydration-mismatch-use-synced-state.mdx';
import MobileNavA11yBottomSheet, {
  metadata as mobileNavA11yMeta,
} from './mobile-nav-a11y-bottom-sheet.mdx';
import FaviconPipelineOneSvg, {
  metadata as faviconPipelineMeta,
} from './favicon-pipeline-one-svg.mdx';
import StandardizingComponentSizeScale, {
  metadata as standardizingSizeScaleMeta,
} from './standardizing-component-size-scale.mdx';
import FormApiAlignmentAria, {
  metadata as formApiAlignmentMeta,
} from './form-api-alignment-aria.mdx';
import TooltipAriaDescribedbyWrongElement, {
  metadata as tooltipAriaDescribedbyMeta,
} from './tooltip-aria-describedby-wrong-element.mdx';
import CiDocsOnlyShellDetection, {
  metadata as ciDocsOnlyShellMeta,
} from './ci-docs-only-shell-detection.mdx';
import CalendlyEmbedTimeoutFallback, {
  metadata as calendlyEmbedTimeoutMeta,
} from './calendly-embed-timeout-fallback.mdx';
import PnpmPhantomDependencies, {
  metadata as pnpmPhantomDependenciesMeta,
} from './pnpm-phantom-dependencies.mdx';
import StaticSiteSearchCmdk, {
  metadata as staticSiteSearchCmdkMeta,
} from './static-site-search-cmdk.mdx';
import PrefersReducedMotionComponentLibrary, {
  metadata as prefersReducedMotionMeta,
} from './prefers-reduced-motion-component-library.mdx';
import CyclingThemeToggle, {
  metadata as cyclingThemeToggleMeta,
} from './cycling-theme-toggle.mdx';
import MinisearchRankedSearchCmdk, {
  metadata as minisearchRankedSearchCmdkMeta,
} from './minisearch-ranked-search-cmdk.mdx';
import FunnelSessionIdAnalytics, {
  metadata as funnelSessionIdAnalyticsMeta,
} from './funnel-session-id-analytics.mdx';

export const blogMdxComponents: Record<AllowedBlogSlugs, ComponentType> = {
  'unified-content-pipeline': UnifiedContentPipeline,
  'auto-generated-toc-scroll-spy': AutoGeneratedTocScrollSpy,
  'visual-regression-ci-pipeline': VisualRegressionCiPipeline,
  'shared-ui-design-system': SharedUiDesignSystem,
  'compose-providers-react-context': ComposeProvidersReactContext,
  'typography-system-nextjs': TypographySystemNextjs,
  'removing-focus-trap-react': RemovingFocusTrapReact,
  'eslint-import-ordering-monorepo': EslintImportOrderingMonorepo,
  'rule-of-three-design-systems': RuleOfThreeDesignSystems,
  'documenting-design-tokens': DocumentingDesignTokens,
  'accessible-dropdown-keyboard-nav': AccessibleDropdownKeyboardNav,
  'toast-pause-on-hover': ToastPauseOnHover,
  'keyboard-navigable-data-tables': KeyboardNavigableDataTables,
  'import-type-circular-dependency': ImportTypeCircularDependency,
  'mobile-bottom-nav-z-index': MobileBottomNavZIndex,
  'graceful-degradation-third-party-embeds':
    GracefulDegradationThirdPartyEmbeds,
  'hydration-mismatch-use-synced-state': HydrationMismatchUseSyncedState,
  'mobile-nav-a11y-bottom-sheet': MobileNavA11yBottomSheet,
  'favicon-pipeline-one-svg': FaviconPipelineOneSvg,
  'standardizing-component-size-scale': StandardizingComponentSizeScale,
  'form-api-alignment-aria': FormApiAlignmentAria,
  'tooltip-aria-describedby-wrong-element': TooltipAriaDescribedbyWrongElement,
  'ci-docs-only-shell-detection': CiDocsOnlyShellDetection,
  'calendly-embed-timeout-fallback': CalendlyEmbedTimeoutFallback,
  'pnpm-phantom-dependencies': PnpmPhantomDependencies,
  'static-site-search-cmdk': StaticSiteSearchCmdk,
  'prefers-reduced-motion-component-library':
    PrefersReducedMotionComponentLibrary,
  'cycling-theme-toggle': CyclingThemeToggle,
  'minisearch-ranked-search-cmdk': MinisearchRankedSearchCmdk,
  'funnel-session-id-analytics': FunnelSessionIdAnalytics,
};

export const blogMdxMetadata: Record<AllowedBlogSlugs, PostMetadata> = {
  'unified-content-pipeline': unifiedPipelineMeta,
  'auto-generated-toc-scroll-spy': tocScrollSpyMeta,
  'visual-regression-ci-pipeline': visualRegressionMeta,
  'shared-ui-design-system': sharedUiDesignSystemMeta,
  'compose-providers-react-context': composeProvidersMeta,
  'typography-system-nextjs': typographySystemMeta,
  'removing-focus-trap-react': removingFocusTrapMeta,
  'eslint-import-ordering-monorepo': eslintImportOrderingMeta,
  'rule-of-three-design-systems': ruleOfThreeMeta,
  'documenting-design-tokens': documentingDesignTokensMeta,
  'accessible-dropdown-keyboard-nav': accessibleDropdownMeta,
  'toast-pause-on-hover': toastPauseOnHoverMeta,
  'keyboard-navigable-data-tables': keyboardNavigableTablesMeta,
  'import-type-circular-dependency': importTypeCircularDependencyMeta,
  'mobile-bottom-nav-z-index': mobileBottomNavZIndexMeta,
  'graceful-degradation-third-party-embeds': gracefulDegradationMeta,
  'hydration-mismatch-use-synced-state': hydrationMismatchMeta,
  'mobile-nav-a11y-bottom-sheet': mobileNavA11yMeta,
  'favicon-pipeline-one-svg': faviconPipelineMeta,
  'standardizing-component-size-scale': standardizingSizeScaleMeta,
  'form-api-alignment-aria': formApiAlignmentMeta,
  'tooltip-aria-describedby-wrong-element': tooltipAriaDescribedbyMeta,
  'ci-docs-only-shell-detection': ciDocsOnlyShellMeta,
  'calendly-embed-timeout-fallback': calendlyEmbedTimeoutMeta,
  'pnpm-phantom-dependencies': pnpmPhantomDependenciesMeta,
  'static-site-search-cmdk': staticSiteSearchCmdkMeta,
  'prefers-reduced-motion-component-library': prefersReducedMotionMeta,
  'cycling-theme-toggle': cyclingThemeToggleMeta,
  'minisearch-ranked-search-cmdk': minisearchRankedSearchCmdkMeta,
  'funnel-session-id-analytics': funnelSessionIdAnalyticsMeta,
};
