import { AllowedBlogSlugs } from '@/types/base';
import { PostMetadata } from '@/types/postTypes';
import { ComponentType } from 'react';

import UnifiedContentPipeline, {
  metadata as unifiedPipelineMeta,
} from './unified-content-pipeline.mdx';

import AutoGeneratedTocScrollSpy, {
  metadata as tocScrollSpyMeta,
} from './auto-generated-toc-scroll-spy.mdx';

import VisualRegressionCiPipeline, {
  metadata as visualRegressionMeta,
} from './visual-regression-ci-pipeline.mdx';

export const blogMdxComponents: Record<AllowedBlogSlugs, ComponentType> = {
  'unified-content-pipeline': UnifiedContentPipeline,
  'auto-generated-toc-scroll-spy': AutoGeneratedTocScrollSpy,
  'visual-regression-ci-pipeline': VisualRegressionCiPipeline,
};

export const blogMdxMetadata: Record<AllowedBlogSlugs, PostMetadata> = {
  'unified-content-pipeline': unifiedPipelineMeta,
  'auto-generated-toc-scroll-spy': tocScrollSpyMeta,
  'visual-regression-ci-pipeline': visualRegressionMeta,
};
