/**
 * Generates the per-type MDX wiring (slug arrays + component/metadata maps) from
 * the .mdx files in apps/root/src/data/content/{blog,projects,experience}.
 *
 * Why this exists: Next.js needs *static* `import` statements to bundle and
 * code-split each MDX component, so the registry can't be a runtime glob (and
 * `import.meta.glob` is Turbopack-only — the prod build is `next build --webpack`).
 * This script emits the same static-import shape the maps used to be hand-written
 * in, so adding a post means dropping the .mdx file — no map edits.
 *
 * Output lives in apps/root/src/data/generated/ (gitignored) and is regenerated
 * on `pnpm install` (postinstall) and before build/test (see apps/root/project.json).
 *
 * Scope: this only generates the component/metadata import maps (the tedious,
 * error-prone part — a missed import silently breaks the build). Slug constants
 * (data/blog.ts etc.) and display order (data/contentOrder.ts) stay hand-authored
 * because slug-array order is load-bearing (About page list, structured-data
 * ItemLists) and project order is curated, not derivable from dates.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, '../apps/root/src/data');
const GENERATED_DIR = path.join(DATA_DIR, 'generated');

// content dir name -> exported variable prefix (note: dir "projects" -> "project")
const TYPES = [
  { dir: 'blog', prefix: 'blog' },
  { dir: 'projects', prefix: 'project' },
  { dir: 'experience', prefix: 'experience' },
] as const;

/** kebab slug -> safe TS identifier fragment (slugs are [a-z0-9-]). */
const ident = (slug: string) => slug.replace(/[^a-zA-Z0-9]/g, '_');

function generateForType(dir: string, prefix: string): number {
  const contentDir = path.join(DATA_DIR, 'content', dir);
  const slugs = fs
    .readdirSync(contentDir)
    .filter(f => f.endsWith('.mdx'))
    .map(f => f.replace(/\.mdx$/, ''))
    .sort();

  const imports = slugs
    .map(
      s =>
        `import C_${ident(s)}, { metadata as M_${ident(s)} } from '@/data/content/${dir}/${s}.mdx';`
    )
    .join('\n');

  const components = slugs.map(s => `  '${s}': C_${ident(s)},`).join('\n');
  const metadata = slugs.map(s => `  '${s}': M_${ident(s)},`).join('\n');

  const out = `// AUTO-GENERATED by scripts/generate-content-registry.ts — do not edit by hand.
// Source: apps/root/src/data/content/${dir}/*.mdx
// Regenerated on \`pnpm install\` (postinstall) and before build/test/typecheck
// (see apps/root/project.json). Gitignored.
/* eslint-disable */
import type { ComponentType } from 'react';
${imports}

export const ${prefix}MdxComponents: Record<string, ComponentType> = {
${components}
};

export const ${prefix}MdxMetadata = {
${metadata}
};
`;

  fs.mkdirSync(GENERATED_DIR, { recursive: true });
  fs.writeFileSync(path.join(GENERATED_DIR, `${dir}.generated.ts`), out);
  return slugs.length;
}

let total = 0;
for (const { dir, prefix } of TYPES) {
  const n = generateForType(dir, prefix);
  total += n;
  console.log(`  ✅ ${dir}: ${n} entries -> generated/${dir}.generated.ts`);
}
console.log(`\n✅ Generated content registry (${total} entries).`);
