import { AllowedBlogSlugs } from '@/types/base';
import { PostThumbnail } from '@/types/postTypes';
import { BLOG_LINK, UNSPLASH_URL } from '@/utils/constants';
import { blogSlugs } from '@/data/blog';

export const blogRecords: Record<AllowedBlogSlugs, PostThumbnail> = {
  [blogSlugs.unifiedContentPipeline]: {
    slug: blogSlugs.unifiedContentPipeline,
    title: 'Building a Unified Content Pipeline with Next.js and MDX',
    description:
      'How I refactored from duplicated per-type data files to a single content registry, cutting the cost of adding new content types from 6+ files to 3.',
    link: {
      label: 'Unified Content Pipeline',
      href: `${BLOG_LINK.href}/${blogSlugs.unifiedContentPipeline}`,
    },
    cover: {
      alt: 'An abstract network of connected nodes glowing in blue',
      src: '/photo-1558494949-ef010cbdcc31',
      origin: `${UNSPLASH_URL}/photos/close-up-photography-of-computer-motherboard-iar-afB0QQw`,
      creator: '@jordanharrison',
      blurHash: 'L25E{Jxu00Rj~qof%Mt700ay-;WB',
    },
  },
  [blogSlugs.autoGeneratedTocScrollSpy]: {
    slug: blogSlugs.autoGeneratedTocScrollSpy,
    title: 'Building an Auto-Generated Table of Contents with Scroll Spy',
    description:
      'A responsive, accessible TOC that extracts headings from rendered MDX, tracks reading position with IntersectionObserver, and adapts between a sticky sidebar and a mobile bottom sheet.',
    link: {
      label: 'Auto-Generated TOC',
      href: `${BLOG_LINK.href}/${blogSlugs.autoGeneratedTocScrollSpy}`,
    },
    cover: {
      alt: 'A clean desk with an open notebook showing a table of contents',
      src: '/photo-1456324504439-367cee3b3c32',
      origin: `${UNSPLASH_URL}/photos/white-book-page-on-white-textile-MldQeWmF2_g`,
      creator: '@aaronburden',
      blurHash: 'LNKdT3~qt7%M%Mj[ofj[_3M{j[WB',
    },
  },
  [blogSlugs.visualRegressionCiPipeline]: {
    slug: blogSlugs.visualRegressionCiPipeline,
    title: 'Automating Visual Regression Testing in GitHub Actions',
    description:
      'A CI pipeline that catches visual regressions with Playwright screenshots, auto-updates baselines via workflow dispatch, and re-triggers itself using a PAT.',
    link: {
      label: 'Visual Regression CI',
      href: `${BLOG_LINK.href}/${blogSlugs.visualRegressionCiPipeline}`,
    },
    cover: {
      alt: 'A monitor displaying lines of code in a dark editor',
      src: '/photo-1555066931-4365d14bab8c',
      origin: `${UNSPLASH_URL}/photos/black-and-silver-laptop-computer-on-table-4hbJ-eymZ1o`,
      creator: '@luca_bravo',
      blurHash: 'L37UxT-:00NG~qt7-:NG00xu9FRj',
    },
  },
};
