import { AllowedBlogSlugs } from '@/types/base';
import { PostThumbnail } from '@/types/postTypes';
import { BLOG_LINK, UNSPLASH_URL } from '@/utils/constants';
import { blogSlugs } from '@/data/blog';

export const blogRecords: Record<AllowedBlogSlugs, PostThumbnail> = {
  [blogSlugs.unifiedContentPipeline]: {
    slug: blogSlugs.unifiedContentPipeline,
    title: 'Building a Unified Content Pipeline with Next.js and MDX',
    description:
      'How I refactored from duplicated per-type data files to a single content registry, cutting the cost of adding new content types from 6+ files to 3.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.unifiedContentPipeline}`,
    },
    cover: {
      alt: 'An abstract network of connected nodes glowing in blue',
      src: '/photo-1558494949-ef010cbdcc31',
      origin: `${UNSPLASH_URL}/photos/close-up-photography-of-computer-motherboard-iar-afB0QQw`,
      creator: '@jordanharrison',
    },
  },
  [blogSlugs.autoGeneratedTocScrollSpy]: {
    slug: blogSlugs.autoGeneratedTocScrollSpy,
    title: 'Building an Auto-Generated Table of Contents with Scroll Spy',
    description:
      'A responsive, accessible TOC that extracts headings from rendered MDX, tracks reading position with IntersectionObserver, and adapts between a sticky sidebar and a mobile bottom sheet.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.autoGeneratedTocScrollSpy}`,
    },
    cover: {
      alt: 'A clean desk with an open notebook showing a table of contents',
      src: '/photo-1456324504439-367cee3b3c32',
      origin: `${UNSPLASH_URL}/photos/white-book-page-on-white-textile-MldQeWmF2_g`,
      creator: '@aaronburden',
    },
  },
  [blogSlugs.visualRegressionCiPipeline]: {
    slug: blogSlugs.visualRegressionCiPipeline,
    title: 'Automating Visual Regression Testing in GitHub Actions',
    description:
      'A CI pipeline that catches visual regressions with Playwright screenshots, auto-updates baselines via workflow dispatch, and re-triggers itself using a PAT.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.visualRegressionCiPipeline}`,
    },
    cover: {
      alt: 'A monitor displaying lines of code in a dark editor',
      src: '/photo-1555066931-4365d14bab8c',
      origin: `${UNSPLASH_URL}/photos/black-and-silver-laptop-computer-on-table-4hbJ-eymZ1o`,
      creator: '@luca_bravo',
    },
  },
  [blogSlugs.sharedUiDesignSystem]: {
    slug: blogSlugs.sharedUiDesignSystem,
    title:
      'From Wrapper Hell to a Single Source of Truth: Consolidating a Design System',
    description:
      'How I eliminated 2,000 lines of duplication by promoting kit wrappers into a shared-ui component library, enforcing typography variants, and establishing layout primitives with sensible defaults.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.sharedUiDesignSystem}`,
    },
    cover: {
      alt: 'Neatly organized colorful building blocks arranged in a grid pattern',
      src: '/photo-1581783898377-1c85bf937427',
      origin: `${UNSPLASH_URL}/photos/assorted-color-brick-lot-HpMihL323k0`,
      creator: '@marjan_blan',
    },
  },
  [blogSlugs.composeProvidersReactContext]: {
    slug: blogSlugs.composeProvidersReactContext,
    title: 'Composing React Providers Without the Nesting Nightmare',
    description:
      'A functional composition pattern that turns deeply nested provider trees into a flat, readable list — with automatic React DevTools display names.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.composeProvidersReactContext}`,
    },
    cover: {
      alt: 'Colorful interlocking puzzle pieces on a white surface',
      src: '/photo-1494059980473-813e73ee784b',
      origin: `${UNSPLASH_URL}/photos/multicolored-abstract-painting-bU6JyhSI6zo`,
      creator: '@pawel_czerwinski',
    },
  },
  [blogSlugs.typographySystemNextjs]: {
    slug: blogSlugs.typographySystemNextjs,
    title: 'Building a Typography System for a Next.js Design System',
    description:
      'How I audited three competing heading systems, designed a variant-based Heading/Text API, and migrated 20+ files to a single typography source of truth.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.typographySystemNextjs}`,
    },
    cover: {
      alt: 'Wooden letterpress type blocks arranged in rows',
      src: '/photo-1455659817273-f96807779a8a',
      origin: `${UNSPLASH_URL}/photos/assorted-type-letters-Y6tGu-OH8lA`,
      creator: '@amadorloureiro',
    },
  },
  [blogSlugs.removingFocusTrapReact]: {
    slug: blogSlugs.removingFocusTrapReact,
    title: 'Removing focus-trap-react: Native Focus Management in Modals',
    description:
      'Why we removed a 15KB dependency from our shared-ui library and replaced it with native dialog behavior and manual focus management.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.removingFocusTrapReact}`,
    },
    cover: {
      alt: 'A close-up of a keyboard with a glowing focus indicator',
      src: '/photo-1587829741301-dc798b83add3',
      origin: `${UNSPLASH_URL}/photos/black-computer-keyboard-7WfBMtB-RhE`,
      creator: '@eylumandemin',
    },
  },
  [blogSlugs.eslintImportOrderingMonorepo]: {
    slug: blogSlugs.eslintImportOrderingMonorepo,
    title: 'ESLint Import Ordering for Monorepos: Taming 77 Violations',
    description:
      'Setting up import/order with custom path groups for monorepo aliases, fixing ESLint 10 compatibility, and auto-fixing 77 violations across the codebase.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.eslintImportOrderingMonorepo}`,
    },
    cover: {
      alt: 'Neatly organized files in a filing cabinet',
      src: '/photo-1544396821-4dd40b938ad3',
      origin: `${UNSPLASH_URL}/photos/assorted-files-Q9y3LRuuxmg`,
      creator: '@samuelzeller',
    },
  },
  [blogSlugs.ruleOfThreeDesignSystems]: {
    slug: blogSlugs.ruleOfThreeDesignSystems,
    title: 'The Rule of Three in Design Systems',
    description:
      'When to extract a repeated pattern into a shared abstraction — and when to leave it inline. A practical framework from auditing typography.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.ruleOfThreeDesignSystems}`,
    },
    cover: {
      alt: 'Three identical geometric shapes casting different shadows',
      src: '/photo-1509228468518-180dd4864904',
      origin: `${UNSPLASH_URL}/photos/brown-wooden-blocks-on-white-surface-s9CC2SKySJM`,
      creator: '@brett_jordan',
    },
  },
  [blogSlugs.documentingDesignTokens]: {
    slug: blogSlugs.documentingDesignTokens,
    title: 'Documenting Design Tokens for Developer Experience',
    description:
      'Why a comprehensive theme token reference is part of the design system — not an afterthought — and how we documented 100+ tokens.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.documentingDesignTokens}`,
    },
    cover: {
      alt: 'An open style guide book with color swatches and typography samples',
      src: '/photo-1507842217343-583bb7270b66',
      origin: `${UNSPLASH_URL}/photos/library-photo-YLSwjSy7stw`,
      creator: '@iamtm',
    },
  },
  [blogSlugs.accessibleDropdownKeyboardNav]: {
    slug: blogSlugs.accessibleDropdownKeyboardNav,
    title: 'Building an Accessible Dropdown Without a Library',
    description:
      'Full ARIA menu semantics and keyboard navigation in ~150 lines of React — no Radix, no Headless UI, just the spec.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.accessibleDropdownKeyboardNav}`,
    },
    cover: {
      alt: 'A keyboard with illuminated keys in a dark environment',
      src: '/photo-1541140532154-b024d6e1841f',
      origin: `${UNSPLASH_URL}/photos/black-computer-keyboard-in-close-up-photography-mP7aPSUm7aE`,
      creator: '@nubelson',
    },
  },
  [blogSlugs.toastPauseOnHover]: {
    slug: blogSlugs.toastPauseOnHover,
    title: 'Pause-on-Hover: Making Toast Notifications Respect the User',
    description:
      'Adding aria-live regions and pause-on-hover to a Toast system — where screen readers and sighted users have conflicting timing needs.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.toastPauseOnHover}`,
    },
    cover: {
      alt: 'A notification bell icon on a blurred background',
      src: '/photo-1514464750060-00e6e34c8b8c',
      origin: `${UNSPLASH_URL}/photos/white-and-brown-round-frame-dMeEJRE18VI`,
      creator: '@joshcala',
    },
  },
  [blogSlugs.keyboardNavigableDataTables]: {
    slug: blogSlugs.keyboardNavigableDataTables,
    title: 'Making Data Tables Keyboard-Navigable',
    description:
      'Adding scope, caption, clickable row keyboard support, and focus-visible to a Table component — the accessibility basics HTML tables need but rarely get.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.keyboardNavigableDataTables}`,
    },
    cover: {
      alt: 'A spreadsheet displayed on a monitor screen',
      src: '/photo-1460925895917-afdab827c52f',
      origin: `${UNSPLASH_URL}/photos/laptop-computer-on-glass-top-table-hpjSkU2UYSU`,
      creator: '@carlheyerdahl',
    },
  },
  [blogSlugs.importTypeCircularDependency]: {
    slug: blogSlugs.importTypeCircularDependency,
    title:
      "When import type Isn't Optional: Fixing a Circular Dependency Crash",
    description:
      'A production crash caused by a subtle difference between import and import type in a Turbopack-bundled Next.js app.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.importTypeCircularDependency}`,
    },
    cover: {
      alt: 'Tangled cables forming a circular loop',
      src: '/photo-1558618666-fcd25c85f82e',
      origin: `${UNSPLASH_URL}/photos/close-up-photo-of-cables-plugged-into-the-server-bUWBWMH0kE0`,
      creator: '@thomasjsn',
    },
  },
  [blogSlugs.mobileBottomNavZIndex]: {
    slug: blogSlugs.mobileBottomNavZIndex,
    title: 'Designing a Mobile Bottom Nav That Plays Nice with FABs and Sheets',
    description:
      'The z-index choreography behind adding a fixed bottom bar without breaking scroll-to-top, table-of-contents, and bottom sheet overlays.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.mobileBottomNavZIndex}`,
    },
    cover: {
      alt: 'A layered architectural structure showing different levels',
      src: '/photo-1486406146926-c627a92ad1ab',
      origin: `${UNSPLASH_URL}/photos/low-angle-photography-of-gray-building-at-daytime-yEauzeZU6xo`,
      creator: '@aronvisuals',
    },
  },
  [blogSlugs.gracefulDegradationThirdPartyEmbeds]: {
    slug: blogSlugs.gracefulDegradationThirdPartyEmbeds,
    title: 'Graceful Degradation for Third-Party Embeds',
    description:
      'Adding a timeout-based fallback when a Calendly iframe gets blocked by ad blockers or network issues.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.gracefulDegradationThirdPartyEmbeds}`,
    },
    cover: {
      alt: 'A safety net stretched beneath a high structure',
      src: '/photo-1504639725590-34d0984388bd',
      origin: `${UNSPLASH_URL}/photos/macbook-pro-on-brown-wooden-table-8qEB0fTe9Vw`,
      creator: '@kevinku',
    },
  },
  [blogSlugs.hydrationMismatchUseSyncedState]: {
    slug: blogSlugs.hydrationMismatchUseSyncedState,
    title: 'Fixing Hydration Mismatches Without Suppressing Them',
    description:
      'A three-line useSyncExternalStore hook that defers client-only state so server and client renders agree — no suppressHydrationWarning needed.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.hydrationMismatchUseSyncedState}`,
    },
    cover: {
      alt: 'Two puzzle pieces fitting together on a clean surface',
      src: '/photo-1494412574643-ff11b0a5eb95',
      origin: `${UNSPLASH_URL}/photos/two-white-and-red-dices-FO7bKvgETgQ`,
      creator: '@brett_jordan',
    },
  },
  [blogSlugs.mobileNavA11yBottomSheet]: {
    slug: blogSlugs.mobileNavA11yBottomSheet,
    title: 'Mobile Nav Accessibility: The Bottom Sheet Dialog Pattern',
    description:
      'A nav redesign passed code review but failed 6 E2E tests on mobile — here is what axe caught and how aria-hidden, inert, and proper dialog semantics fixed it.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.mobileNavA11yBottomSheet}`,
    },
    cover: {
      alt: 'A smartphone displaying a mobile application interface',
      src: '/photo-1512941937669-90a1b58e7e9c',
      origin: `${UNSPLASH_URL}/photos/person-holding-space-gray-iphone-6-B5PBTIg1wts`,
      creator: '@freestocks',
    },
  },
  [blogSlugs.faviconPipelineOneSvg]: {
    slug: blogSlugs.faviconPipelineOneSvg,
    title: 'A Favicon Pipeline from One SVG',
    description:
      'A 64-line bash script that generates 11 SEO-ready images from a single SVG — favicon.ico, apple-touch-icon, android-chrome, and mstile — using rsvg-convert and ImageMagick.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.faviconPipelineOneSvg}`,
    },
    cover: {
      alt: 'A terminal window showing command-line output',
      src: '/photo-1629654297299-c8506221ca97',
      origin: `${UNSPLASH_URL}/photos/a-computer-screen-with-a-bunch-of-text-on-it-m_HRfLhgABo`,
      creator: '@garrettsears',
    },
  },
  [blogSlugs.standardizingComponentSizeScale]: {
    slug: blogSlugs.standardizingComponentSizeScale,
    title: 'Standardizing a Component Size Scale Across 20 Components',
    description:
      'A design system with five avatar sizes, no badge size, and three spinner sizes is a design system arguing with itself.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.standardizingComponentSizeScale}`,
    },
    cover: {
      alt: 'A ruler and tape measure for precise measurement',
      src: '/photo-1550985543-49bee3167284',
      origin: `${UNSPLASH_URL}/photos/ruler-tape-measure-precision`,
      creator: '@unsplash',
    },
  },
  [blogSlugs.formApiAlignmentAria]: {
    slug: blogSlugs.formApiAlignmentAria,
    title: 'Aligning Five Form Components Around aria-describedby',
    description:
      'Five form components, five approaches to error display. We aligned them around a single accessibility pattern.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.formApiAlignmentAria}`,
    },
    cover: {
      alt: 'A person filling out a form on a clipboard',
      src: '/photo-1522542550221-31fd19575a2d',
      origin: `${UNSPLASH_URL}/photos/person-writing-on-white-paper-GJao3ZTX9gU`,
      creator: '@helloquence',
    },
  },
  [blogSlugs.tooltipAriaDescribedbyWrongElement]: {
    slug: blogSlugs.tooltipAriaDescribedbyWrongElement,
    title: 'Tooltip aria-describedby Was on the Wrong Element',
    description:
      'Our Tooltip passed every test but put aria-describedby on a wrapper div instead of the trigger element. Screen readers never announced it.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.tooltipAriaDescribedbyWrongElement}`,
    },
    cover: {
      alt: 'Speech bubbles in a conversation',
      src: '/photo-1694878981888-7a526050b455',
      origin: `${UNSPLASH_URL}/photos/speech-bubble-conversation-popup`,
      creator: '@unsplash',
    },
  },
  [blogSlugs.ciDocsOnlyShellDetection]: {
    slug: blogSlugs.ciDocsOnlyShellDetection,
    title: 'Replacing a GitHub Action with 15 Lines of Shell',
    description:
      'dorny/paths-filter silently ignored our config. We replaced it with a shell case statement that actually works.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.ciDocsOnlyShellDetection}`,
    },
    cover: {
      alt: 'A funnel filtering and sorting items',
      src: '/photo-1652785099864-1c6fd016c950',
      origin: `${UNSPLASH_URL}/photos/filter-funnel-sieve-sorting`,
      creator: '@unsplash',
    },
  },
  [blogSlugs.calendlyEmbedTimeoutFallback]: {
    slug: blogSlugs.calendlyEmbedTimeoutFallback,
    title: 'An 8-Second Timeout for Third-Party Iframes',
    description:
      "An iframe that never loads looks like a broken page. We added a timeout with a direct booking link so users aren't left staring at a spinner.",
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.calendlyEmbedTimeoutFallback}`,
    },
    cover: {
      alt: 'An hourglass with sand flowing through it',
      src: '/photo-1640609432611-f4e2ae26898c',
      origin: `${UNSPLASH_URL}/photos/hourglass-timer-waiting-sand`,
      creator: '@unsplash',
    },
  },
  [blogSlugs.pnpmPhantomDependencies]: {
    slug: blogSlugs.pnpmPhantomDependencies,
    title:
      'Phantom Dependencies: What pnpm Strict Mode Reveals About Your Monorepo',
    description:
      'Migrating from Yarn Classic to pnpm exposes dependencies that worked by accident, not by declaration.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.pnpmPhantomDependencies}`,
    },
    cover: {
      alt: 'Tangled wires and messy cables',
      src: '/photo-1621294465978-6b4198a5f2f7',
      origin: `${UNSPLASH_URL}/photos/tangled-wires-messy-cables`,
      creator: '@unsplash',
    },
  },
  [blogSlugs.staticSiteSearchCmdk]: {
    slug: blogSlugs.staticSiteSearchCmdk,
    title: 'Site Search Without a Server: Static Index and cmdk',
    description:
      'A build-time search index and cmdk power Cmd+K search across 47 pages with zero API calls.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.staticSiteSearchCmdk}`,
    },
    cover: {
      alt: 'A command palette interface on a dark screen',
      src: '/photo-1668854040739-c5958f25f8f8',
      origin: `${UNSPLASH_URL}/photos/command-palette-keyboard-shortcut`,
      creator: '@unsplash',
    },
  },
  [blogSlugs.prefersReducedMotionComponentLibrary]: {
    slug: blogSlugs.prefersReducedMotionComponentLibrary,
    title: 'Systematic prefers-reduced-motion Across a Component Library',
    description:
      'Auditing every animated component for motion sensitivity reveals which animations are decorative and which need static alternatives.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.prefersReducedMotionComponentLibrary}`,
    },
    cover: {
      alt: 'A slow-motion water droplet frozen in time',
      src: '/photo-1606214554814-e8a9f97bdbb0',
      origin: `${UNSPLASH_URL}/photos/slow-motion-water-droplet-frozen`,
      creator: '@unsplash',
    },
  },
  [blogSlugs.cyclingThemeToggle]: {
    slug: blogSlugs.cyclingThemeToggle,
    title: 'Cycling Theme Toggle: From Radio Group to Single Button',
    description:
      'Replacing a three-button theme picker with a single cycling button and a keyboard shortcut reclaims nav space without losing discoverability.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.cyclingThemeToggle}`,
    },
    cover: {
      alt: 'A sunrise and sunset gradient on the horizon',
      src: '/photo-1534568292380-49954e6859e8',
      origin: `${UNSPLASH_URL}/photos/sunrise-sunset-horizon-gradient`,
      creator: '@unsplash',
    },
  },
  [blogSlugs.minisearchRankedSearchCmdk]: {
    slug: blogSlugs.minisearchRankedSearchCmdk,
    title: 'Upgrading cmdk Search with MiniSearch Field Boosting',
    description:
      'cmdk does substring matching. We kept its UI shell and replaced the filter engine with MiniSearch for ranked, fuzzy results with match highlighting.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.minisearchRankedSearchCmdk}`,
    },
    cover: {
      alt: 'Search results with ranked filters on a screen',
      src: '/photo-1519162721257-18cd195350c2',
      origin: `${UNSPLASH_URL}/photos/search-results-ranking-filter`,
      creator: '@unsplash',
    },
  },
  [blogSlugs.funnelSessionIdAnalytics]: {
    slug: blogSlugs.funnelSessionIdAnalytics,
    title: 'Correlating a Multi-Step Funnel with One sessionStorage ID',
    description:
      'A timestamp and random suffix in sessionStorage ties scan, completion, email capture, and calendar booking into one GA4 funnel with zero backend state.',
    link: {
      href: `${BLOG_LINK.href}/${blogSlugs.funnelSessionIdAnalytics}`,
    },
    cover: {
      alt: 'A funnel pouring colored liquid into a glass flask',
      src: '/photo-1532187863486-abf9dbad1b69',
      origin: `${UNSPLASH_URL}/photos/funnel-pouring-liquid-flask`,
      creator: '@unsplash',
    },
  },
};
