export const blogSlugs = {
  unifiedContentPipeline: 'unified-content-pipeline',
  autoGeneratedTocScrollSpy: 'auto-generated-toc-scroll-spy',
  visualRegressionCiPipeline: 'visual-regression-ci-pipeline',
  sharedUiDesignSystem: 'shared-ui-design-system',
  composeProvidersReactContext: 'compose-providers-react-context',
  typographySystemNextjs: 'typography-system-nextjs',
  removingFocusTrapReact: 'removing-focus-trap-react',
  eslintImportOrderingMonorepo: 'eslint-import-ordering-monorepo',
  ruleOfThreeDesignSystems: 'rule-of-three-design-systems',
  documentingDesignTokens: 'documenting-design-tokens',
  accessibleDropdownKeyboardNav: 'accessible-dropdown-keyboard-nav',
  toastPauseOnHover: 'toast-pause-on-hover',
  keyboardNavigableDataTables: 'keyboard-navigable-data-tables',
  importTypeCircularDependency: 'import-type-circular-dependency',
  mobileBottomNavZIndex: 'mobile-bottom-nav-z-index',
  gracefulDegradationThirdPartyEmbeds:
    'graceful-degradation-third-party-embeds',
  hydrationMismatchUseSyncedState: 'hydration-mismatch-use-synced-state',
  mobileNavA11yBottomSheet: 'mobile-nav-a11y-bottom-sheet',
  faviconPipelineOneSvg: 'favicon-pipeline-one-svg',
} as const;

export const blogPageSlugs = [...Object.values(blogSlugs)];
