import { AllowedBlogSlugs } from '@/types/base';
import { PostThumbnail } from '@/types/postTypes';
import { BLOG_LINK, UNSPLASH_URL } from '@/utils/constants';
import { blogSlugs } from '@/data/blog';

export const blogRecords: Record<AllowedBlogSlugs, PostThumbnail> = {
  [blogSlugs.unifiedContentPipeline]: {
    slug: blogSlugs.unifiedContentPipeline,
    title: 'Building a Unified Content Pipeline with Next.js and MDX',
    description:
      'How I refactored from duplicated per-type data files to a single content registry, cutting the cost of adding new content types from 6+ files to 3.',
    link: {
      label: 'Unified Content Pipeline',
      href: `${BLOG_LINK.href}/${blogSlugs.unifiedContentPipeline}`,
    },
    cover: {
      alt: 'An abstract network of connected nodes glowing in blue',
      src: '/photo-1558494949-ef010cbdcc31',
      origin: `${UNSPLASH_URL}/photos/close-up-photography-of-computer-motherboard-iar-afB0QQw`,
      creator: '@jordanharrison',
      blurHash: 'L25E{Jxu00Rj~qof%Mt700ay-;WB',
    },
  },
  [blogSlugs.autoGeneratedTocScrollSpy]: {
    slug: blogSlugs.autoGeneratedTocScrollSpy,
    title: 'Building an Auto-Generated Table of Contents with Scroll Spy',
    description:
      'A responsive, accessible TOC that extracts headings from rendered MDX, tracks reading position with IntersectionObserver, and adapts between a sticky sidebar and a mobile bottom sheet.',
    link: {
      label: 'Auto-Generated TOC',
      href: `${BLOG_LINK.href}/${blogSlugs.autoGeneratedTocScrollSpy}`,
    },
    cover: {
      alt: 'A clean desk with an open notebook showing a table of contents',
      src: '/photo-1456324504439-367cee3b3c32',
      origin: `${UNSPLASH_URL}/photos/white-book-page-on-white-textile-MldQeWmF2_g`,
      creator: '@aaronburden',
      blurHash: 'LNKdT3~qt7%M%Mj[ofj[_3M{j[WB',
    },
  },
  [blogSlugs.visualRegressionCiPipeline]: {
    slug: blogSlugs.visualRegressionCiPipeline,
    title: 'Automating Visual Regression Testing in GitHub Actions',
    description:
      'A CI pipeline that catches visual regressions with Playwright screenshots, auto-updates baselines via workflow dispatch, and re-triggers itself using a PAT.',
    link: {
      label: 'Visual Regression CI',
      href: `${BLOG_LINK.href}/${blogSlugs.visualRegressionCiPipeline}`,
    },
    cover: {
      alt: 'A monitor displaying lines of code in a dark editor',
      src: '/photo-1555066931-4365d14bab8c',
      origin: `${UNSPLASH_URL}/photos/black-and-silver-laptop-computer-on-table-4hbJ-eymZ1o`,
      creator: '@luca_bravo',
      blurHash: 'L37UxT-:00NG~qt7-:NG00xu9FRj',
    },
  },
  [blogSlugs.sharedUiDesignSystem]: {
    slug: blogSlugs.sharedUiDesignSystem,
    title:
      'From Wrapper Hell to a Single Source of Truth: Consolidating a Design System',
    description:
      'How I eliminated 2,000 lines of duplication by promoting kit wrappers into a shared-ui component library, enforcing typography variants, and establishing layout primitives with sensible defaults.',
    link: {
      label: 'Design System Consolidation',
      href: `${BLOG_LINK.href}/${blogSlugs.sharedUiDesignSystem}`,
    },
    cover: {
      alt: 'Neatly organized colorful building blocks arranged in a grid pattern',
      src: '/photo-1581783898377-1c85bf937427',
      origin: `${UNSPLASH_URL}/photos/assorted-color-brick-lot-HpMihL323k0`,
      creator: '@marjan_blan',
      blurHash: 'LKHe2RD%00%M_3WBt7Rj~qxuIUj[',
    },
  },
  [blogSlugs.composeProvidersReactContext]: {
    slug: blogSlugs.composeProvidersReactContext,
    title: 'Composing React Providers Without the Nesting Nightmare',
    description:
      'A functional composition pattern that turns deeply nested provider trees into a flat, readable list — with automatic React DevTools display names.',
    link: {
      label: 'Composing React Providers',
      href: `${BLOG_LINK.href}/${blogSlugs.composeProvidersReactContext}`,
    },
    cover: {
      alt: 'Colorful interlocking puzzle pieces on a white surface',
      src: '/photo-1494059980473-813e73ee784b',
      origin: `${UNSPLASH_URL}/photos/multicolored-abstract-painting-bU6JyhSI6zo`,
      creator: '@pawel_czerwinski',
      blurHash: 'LGF~o]_N~q%M%MRjIUj[-;WBD%WB',
    },
  },
  [blogSlugs.typographySystemNextjs]: {
    slug: blogSlugs.typographySystemNextjs,
    title: 'Building a Typography System for a Next.js Design System',
    description:
      'How I audited three competing heading systems, designed a variant-based Heading/Text API, and migrated 20+ files to a single typography source of truth.',
    link: {
      label: 'Typography System',
      href: `${BLOG_LINK.href}/${blogSlugs.typographySystemNextjs}`,
    },
    cover: {
      alt: 'Wooden letterpress type blocks arranged in rows',
      src: '/photo-1455659817273-f96807779a8a',
      origin: `${UNSPLASH_URL}/photos/assorted-type-letters-Y6tGu-OH8lA`,
      creator: '@amadorloureiro',
      blurHash: 'LBF~T5-;00IU~qt7-;RjD%WBM{of',
    },
  },
  [blogSlugs.removingFocusTrapReact]: {
    slug: blogSlugs.removingFocusTrapReact,
    title: 'Removing focus-trap-react: Native Focus Management in Modals',
    description:
      'Why we removed a 15KB dependency from our shared-ui library and replaced it with native dialog behavior and manual focus management.',
    link: {
      label: 'Removing focus-trap-react',
      href: `${BLOG_LINK.href}/${blogSlugs.removingFocusTrapReact}`,
    },
    cover: {
      alt: 'A close-up of a keyboard with a glowing focus indicator',
      src: '/photo-1587829741301-dc798b83add3',
      origin: `${UNSPLASH_URL}/photos/black-computer-keyboard-7WfBMtB-RhE`,
      creator: '@eylumandemin',
      blurHash: 'L24o;G9F00D%~q%MRjRj00of-;WB',
    },
  },
  [blogSlugs.eslintImportOrderingMonorepo]: {
    slug: blogSlugs.eslintImportOrderingMonorepo,
    title: 'ESLint Import Ordering for Monorepos: Taming 77 Violations',
    description:
      'Setting up import/order with custom path groups for monorepo aliases, fixing ESLint 10 compatibility, and auto-fixing 77 violations across the codebase.',
    link: {
      label: 'ESLint Import Ordering',
      href: `${BLOG_LINK.href}/${blogSlugs.eslintImportOrderingMonorepo}`,
    },
    cover: {
      alt: 'Neatly organized files in a filing cabinet',
      src: '/photo-1544396821-4dd40b938ad3',
      origin: `${UNSPLASH_URL}/photos/assorted-files-Q9y3LRuuxmg`,
      creator: '@samuelzeller',
      blurHash: 'LHH_]n~q00M{IU%MIUof~q%MWBRj',
    },
  },
  [blogSlugs.ruleOfThreeDesignSystems]: {
    slug: blogSlugs.ruleOfThreeDesignSystems,
    title: 'The Rule of Three in Design Systems',
    description:
      'When to extract a repeated pattern into a shared abstraction — and when to leave it inline. A practical framework from auditing typography.',
    link: {
      label: 'Rule of Three',
      href: `${BLOG_LINK.href}/${blogSlugs.ruleOfThreeDesignSystems}`,
    },
    cover: {
      alt: 'Three identical geometric shapes casting different shadows',
      src: '/photo-1509228468518-180dd4864904',
      origin: `${UNSPLASH_URL}/photos/brown-wooden-blocks-on-white-surface-s9CC2SKySJM`,
      creator: '@brett_jordan',
      blurHash: 'LGJH6d~q00%M~qt7-;Rj00WBD%of',
    },
  },
  [blogSlugs.documentingDesignTokens]: {
    slug: blogSlugs.documentingDesignTokens,
    title: 'Documenting Design Tokens for Developer Experience',
    description:
      'Why a comprehensive theme token reference is part of the design system — not an afterthought — and how we documented 100+ tokens.',
    link: {
      label: 'Documenting Design Tokens',
      href: `${BLOG_LINK.href}/${blogSlugs.documentingDesignTokens}`,
    },
    cover: {
      alt: 'An open style guide book with color swatches and typography samples',
      src: '/photo-1507842217343-583bb7270b66',
      origin: `${UNSPLASH_URL}/photos/library-photo-YLSwjSy7stw`,
      creator: '@iamtm',
      blurHash: 'L99ZoLxu4n%M~qWBt7RjD%M{M{Rj',
    },
  },
  [blogSlugs.accessibleDropdownKeyboardNav]: {
    slug: blogSlugs.accessibleDropdownKeyboardNav,
    title: 'Building an Accessible Dropdown Without a Library',
    description:
      'Full ARIA menu semantics and keyboard navigation in ~150 lines of React — no Radix, no Headless UI, just the spec.',
    link: {
      label: 'Accessible Dropdown',
      href: `${BLOG_LINK.href}/${blogSlugs.accessibleDropdownKeyboardNav}`,
    },
    cover: {
      alt: 'A keyboard with illuminated keys in a dark environment',
      src: '/photo-1541140532154-b024d6e1841f',
      origin: `${UNSPLASH_URL}/photos/black-computer-keyboard-in-close-up-photography-mP7aPSUm7aE`,
      creator: '@nubelson',
      blurHash: 'L15E{J-;00Rj~q%M-;WB00WBD%of',
    },
  },
  [blogSlugs.toastPauseOnHover]: {
    slug: blogSlugs.toastPauseOnHover,
    title: 'Pause-on-Hover: Making Toast Notifications Respect the User',
    description:
      'Adding aria-live regions and pause-on-hover to a Toast system — where screen readers and sighted users have conflicting timing needs.',
    link: {
      label: 'Toast Pause-on-Hover',
      href: `${BLOG_LINK.href}/${blogSlugs.toastPauseOnHover}`,
    },
    cover: {
      alt: 'A notification bell icon on a blurred background',
      src: '/photo-1514464750060-00e6e34c8b8c',
      origin: `${UNSPLASH_URL}/photos/white-and-brown-round-frame-dMeEJRE18VI`,
      creator: '@joshcala',
      blurHash: 'LGKd$M~q00%M~qof-;Rj00WBD%of',
    },
  },
  [blogSlugs.keyboardNavigableDataTables]: {
    slug: blogSlugs.keyboardNavigableDataTables,
    title: 'Making Data Tables Keyboard-Navigable',
    description:
      'Adding scope, caption, clickable row keyboard support, and focus-visible to a Table component — the accessibility basics HTML tables need but rarely get.',
    link: {
      label: 'Keyboard-Navigable Tables',
      href: `${BLOG_LINK.href}/${blogSlugs.keyboardNavigableDataTables}`,
    },
    cover: {
      alt: 'A spreadsheet displayed on a monitor screen',
      src: '/photo-1460925895917-afdab827c52f',
      origin: `${UNSPLASH_URL}/photos/laptop-computer-on-glass-top-table-hpjSkU2UYSU`,
      creator: '@carlheyerdahl',
      blurHash: 'L26*n%~q00xu-;j[ofWB00of%Mxu',
    },
  },
  [blogSlugs.importTypeCircularDependency]: {
    slug: blogSlugs.importTypeCircularDependency,
    title:
      "When import type Isn't Optional: Fixing a Circular Dependency Crash",
    description:
      'A production crash caused by a subtle difference between import and import type in a Turbopack-bundled Next.js app.',
    link: {
      label: 'import type Circular Dependency',
      href: `${BLOG_LINK.href}/${blogSlugs.importTypeCircularDependency}`,
    },
    cover: {
      alt: 'Tangled cables forming a circular loop',
      src: '/photo-1558618666-fcd25c85f82e',
      origin: `${UNSPLASH_URL}/photos/close-up-photo-of-cables-plugged-into-the-server-bUWBWMH0kE0`,
      creator: '@thomasjsn',
      blurHash: 'L24o;G9F00D%~q%MRjRj00of-;WB',
    },
  },
  [blogSlugs.mobileBottomNavZIndex]: {
    slug: blogSlugs.mobileBottomNavZIndex,
    title: 'Designing a Mobile Bottom Nav That Plays Nice with FABs and Sheets',
    description:
      'The z-index choreography behind adding a fixed bottom bar without breaking scroll-to-top, table-of-contents, and bottom sheet overlays.',
    link: {
      label: 'Mobile Bottom Nav z-index',
      href: `${BLOG_LINK.href}/${blogSlugs.mobileBottomNavZIndex}`,
    },
    cover: {
      alt: 'A layered architectural structure showing different levels',
      src: '/photo-1486406146926-c627a92ad1ab',
      origin: `${UNSPLASH_URL}/photos/low-angle-photography-of-gray-building-at-daytime-yEauzeZU6xo`,
      creator: '@aronvisuals',
      blurHash: 'L37UxT-:00NG~qt7-:NG00xu9FRj',
    },
  },
  [blogSlugs.gracefulDegradationThirdPartyEmbeds]: {
    slug: blogSlugs.gracefulDegradationThirdPartyEmbeds,
    title: 'Graceful Degradation for Third-Party Embeds',
    description:
      'Adding a timeout-based fallback when a Calendly iframe gets blocked by ad blockers or network issues.',
    link: {
      label: 'Third-Party Embed Fallbacks',
      href: `${BLOG_LINK.href}/${blogSlugs.gracefulDegradationThirdPartyEmbeds}`,
    },
    cover: {
      alt: 'A safety net stretched beneath a high structure',
      src: '/photo-1504639725590-34d0984388bd',
      origin: `${UNSPLASH_URL}/photos/macbook-pro-on-brown-wooden-table-8qEB0fTe9Vw`,
      creator: '@kevinku',
      blurHash: 'LGF~o]_N~q%M%MRjIUj[-;WBD%WB',
    },
  },
};
