export const blogSlugs = {
  unifiedContentPipeline: 'unified-content-pipeline',
  autoGeneratedTocScrollSpy: 'auto-generated-toc-scroll-spy',
  visualRegressionCiPipeline: 'visual-regression-ci-pipeline',
} as const;

export const blogPageSlugs = [...Object.values(blogSlugs)];
