import {
  AllowedProjectSlugs,
  AllowedExperienceSlugs,
  AllowedBlogSlugs,
} from '@/types/base';
import { projectSlugs } from '@/data/project';
import { experienceSlugs } from '@/data/experience';
import { blogSlugs } from '@/data/blog';

export interface PaginationLink {
  slug: string;
  title: string;
  href: string;
}

export interface PostPaginationData {
  prev: PaginationLink;
  next: PaginationLink;
}

/**
 * Project history in chronological order based on git creation dates.
 *
 * Git history:
 *   ui-components-v1       — 2025-09-04
 *   cms-tooling-case-study — 2026-01-11 (Winc, Jun 2015)
 *   component-library      — 2026-01-11 (IB, Mar 2018)
 *   accessibility-serials  — 2026-01-11 (TLC, Sep 2019)
 *   performance-case-study — 2026-01-11 (FightCamp, Nov 2021)
 *   logistics-dashboard    — 2026-01-11 (Contract, May 2023)
 *   portfolio-modern       — 2026-01-11 (Portfolio, Jul 2025)
 *   ui-components-v2       — 2026-01-29
 *   contact-form           — 2026-03-24 (Portfolio, Aug 2025)
 *
 * Entries sharing the same git date are sub-sorted by the chronology
 * of the work they describe.
 */
export const projectHistory: AllowedProjectSlugs[] = [
  projectSlugs.uiV1, // 2025-09-04
  projectSlugs.csCMSTooling, // 2026-01-11 — Winc (Jun 2015)
  projectSlugs.csCLibrary, // 2026-01-11 — Internet Brands (Mar 2018)
  projectSlugs.csA11y, // 2026-01-11 — TLC (Sep 2019)
  projectSlugs.csPerformance, // 2026-01-11 — FightCamp (Nov 2021)
  projectSlugs.csLogisticsDashboard, // 2026-01-11 — Contract (May 2023)
  projectSlugs.csModernPractice, // 2026-01-11 — Portfolio (Jul 2025)
  projectSlugs.uiV2, // 2026-01-29
  projectSlugs.csContactForm, // 2026-03-24 — Portfolio (Aug 2025)
  projectSlugs.csAppContext, // 2026-04-05 — Portfolio (Mar 2026)
];

/**
 * Experience history in chronological order (by employment start date).
 */
export const experienceHistory: AllowedExperienceSlugs[] = [
  experienceSlugs.Winc, // Jun 2015
  experienceSlugs.IB, // Mar 2018
  experienceSlugs.TLC, // Sep 2019
  experienceSlugs.FC, // Nov 2021
  experienceSlugs.SD, // Jan 2023
];

/**
 * Blog history in chronological order (by publish date).
 */
export const blogHistory: AllowedBlogSlugs[] = [
  blogSlugs.unifiedContentPipeline, // 2026-04-03
  blogSlugs.autoGeneratedTocScrollSpy, // 2026-04-04
  blogSlugs.visualRegressionCiPipeline, // 2026-04-04
  blogSlugs.sharedUiDesignSystem, // 2026-04-04
  blogSlugs.composeProvidersReactContext, // 2026-04-05
  blogSlugs.typographySystemNextjs, // 2026-04-05
  blogSlugs.removingFocusTrapReact, // 2026-04-05
  blogSlugs.eslintImportOrderingMonorepo, // 2026-04-05
  blogSlugs.ruleOfThreeDesignSystems, // 2026-04-05
  blogSlugs.documentingDesignTokens, // 2026-04-05
  blogSlugs.accessibleDropdownKeyboardNav, // 2026-04-06
  blogSlugs.toastPauseOnHover, // 2026-04-06
  blogSlugs.keyboardNavigableDataTables, // 2026-04-06
  blogSlugs.importTypeCircularDependency, // 2026-04-06
  blogSlugs.mobileBottomNavZIndex, // 2026-04-06
  blogSlugs.gracefulDegradationThirdPartyEmbeds, // 2026-04-06
  blogSlugs.hydrationMismatchUseSyncedState, // 2026-04-06
  blogSlugs.mobileNavA11yBottomSheet, // 2026-04-06
  blogSlugs.faviconPipelineOneSvg, // 2026-04-06
  blogSlugs.standardizingComponentSizeScale, // 2026-04-07
  blogSlugs.formApiAlignmentAria, // 2026-04-07
  blogSlugs.tooltipAriaDescribedbyWrongElement, // 2026-04-07
  blogSlugs.ciDocsOnlyShellDetection, // 2026-04-07
  blogSlugs.calendlyEmbedTimeoutFallback, // 2026-04-07
  blogSlugs.pnpmPhantomDependencies, // 2026-04-08
  blogSlugs.staticSiteSearchCmdk, // 2026-04-08
  blogSlugs.prefersReducedMotionComponentLibrary, // 2026-04-08
  blogSlugs.cyclingThemeToggle, // 2026-04-08
  blogSlugs.minisearchRankedSearchCmdk, // 2026-04-10
  blogSlugs.funnelSessionIdAnalytics, // 2026-04-10
  blogSlugs.mobileVrDataDrivenPlaywright, // 2026-04-10
  blogSlugs.sentrySkipWithoutDsn, // 2026-04-10
  blogSlugs.mdxSingleSourceOfTruth, // 2026-04-11
  blogSlugs.clientSideTagFilteringSeo, // 2026-04-13
  blogSlugs.storybookInteractionTestsAria, // 2026-04-13
];
